[package]
name = "argh_shared"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
