[package]
name = "argh_derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
argh_shared = { version = "0.1.12", path = "../argh_shared" }

[features]
help = []
